### ISSUE TITLE
not really an issue but very important

### ISSUE THREAD

**Issue by Nick-77ab2** [Flaxbeard/Thaumic_Exploration#13]
(MAKE SURE YOU READ THE WHOLE THING)so i accidently posted this crash on thaumic tinkerer and the owner told me it was thaumic exploration and pointed me toward a jenkins website for a fix from this mod, the only problem was the website she/he put down wasnt a website this is the crash:
 Caused by: java.lang.NoClassDefFoundError: vazkii/tinkerer/common/enchantment/core/EnchantmentManager
    at flaxbeard.thaumicexploration.integration.TTIntegration.registerEnchants(TTIntegration.java:22)
    at flaxbeard.thaumicexploration.ThaumicExploration.load(ThaumicExploration.java:506)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: vazkii.tinkerer.common.enchantment.core.EnchantmentManager
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:99)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)

i was wondering if you could point me in the right direction? i get it with version 0.6.0-0.6.0e now if i change thaumic tinkerer back to version 147 instead of 150 that fixes it

**Comment by Nick-77ab2** [comment]
shoot could you close this? i got the correct link the person resent it
