### ISSUE TITLE
Server Crash when attacking Wither Skeleton with Disarm Enchant

### ISSUE THREAD

**Issue by kingofrunes** [Flaxbeard/Thaumic_Exploration#24]
Doesn't happen all the time, but happens a good chunk of the time that when you attack a Wither Skeleton with a sword enchanted with Disarm it will cause a server crash. Here is the crash log details:

http://pastebin.com/Hyf6VXqf

Short Version of the error:

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:101)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1772)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
    at net.minecraft.entity.monster.EntitySkeleton.func_70636_d(SourceFile:136)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
    at net.minecraft.world.World.func_72866_a(World.java:2068)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2032)
    at net.minecraft.world.World.func_72939_s(World.java:1885)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Salox** [comment]
This issue has resurfaced any idea how to fix this?
 my crash log http://pastebin.com/UqADdVaK
