### ISSUE TITLE
A weird crash

### ISSUE THREAD

**Issue by Mattk4355** [Flaxbeard/Thaumic_Exploration#31]
So I try to load Thaumic Exploration in my custom pack, and it goes fine till it loads Thaumic Exploration, and then it crashes with this:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/23/14 6:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thaumcraft/common/blocks/JarStepSound
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: thaumcraft/common/blocks/JarStepSound
    at flaxbeard.thaumicexploration.ThaumicExploration.preInit(ThaumicExploration.java:347)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: thaumcraft.common.blocks.JarStepSound
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 45 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1299539064 bytes (1239 MB) / 2621964288 bytes (2500 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2056m -Xmx4096m -XX:PermSize=1028m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 Optifine OptiFine_1.7.10_HD_U_B4 129 mods loaded, 129 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1240} [Forge Mod Loader](forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1240} [Minecraft Forge](forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997Core{1.0.2.13} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.68} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.68-universal.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.652-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.652-experimental.jar) Unloaded->Constructed->Pre-initialized
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar) Unloaded->Constructed->Pre-initialized
    AromaBackup{0.0.0.3} [AromaBackup](AromaBackup-1.7.10-0.0.0.3.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.5.1.32} [BD Lib](bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1018-universal.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.2.2} [BuildCraft](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.2.0.5} [Forestry for Minecraft](forestry_1.7.10-3.2.0.5.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized
    BigReactors{0.4.0rc11} [Big Reactors](BigReactors-0.4.0rc11.jar) Unloaded->Constructed->Pre-initialized
    BinnieCore{2.0-dev5} [Binnie Core](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    Botany{2.0-dev5} [Botany](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    ExtraBees{2.0-dev5} [Extra Bees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    ExtraTrees{2.0-dev5} [Extra Trees](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    Genetics{2.0-dev5} [Genetics](binnie-mods-2.0-dev5.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.2.1b} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.2.1b-1.jar) Unloaded->Constructed->Pre-initialized
    WaslieCore{1.1} [WaslieCore](WaslieCore-1.1_B43.jar) Unloaded->Constructed->Pre-initialized
    BloodUtils{1.4} [BloodUtils](BloodUtils-1.4_B0.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.2.0} [Thaumcraft](Thaumcraft-1.7.10-4.2.2.0.jar) Unloaded->Constructed->Pre-initialized
    Botania{r1.3-140} [Botania](Botania r1.3-140.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.2.2} [BC Transport](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.2.2} [BC Silicon](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.2.2} [BC Builders](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.2.2} [BC Energy](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.2.2} [BC Factory](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.2.7} [Carpenter's Blocks](Carpenter's Blocks v3.2.7 - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized
    CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized
    DeathCounter{4.0.0} [DeathCounter](DeathCounter-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC5} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.2.2.285} [Ender IO](EnderIO-1.7.10-2.2.2.285.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.26} [EnderStorage](EnderStorage-1.7.10-1.4.5.26-universal.jar) Unloaded->Constructed->Pre-initialized
    EnderZoo{1.7.10-1.0.5.14} [Ender Zoo](EnderZoo-1.7.10-1.0.5.14.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized
    ForbiddenMagic{1.7.10-0.55} [Forbidden Magic](Forbidden Magic-1.7.10-0.55.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.4.0.0} [Railcraft](Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized
    gendustry{1.4.2.46} [GenDustry](gendustry-mc1710-1.4.2.46.jar) Unloaded->Constructed->Pre-initialized
    GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    IC2NuclearControl{2.0.8b} [Nuclear Control 2](IC2NuclearControl-2.0.8b.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    journeymap{4.0.5} [JourneyMap](JourneyMap4.0.5_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC5} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC4} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC5} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC4} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC4} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC5} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC4} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC4} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC4} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC4} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC4} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC4} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC4} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC5} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC4} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC5} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC5} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.3.11} [NEI Addons](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-231.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-454.jar) Unloaded->Constructed->Pre-initialized
    PowerConverters{1.7.10-3.0.0.32} [Power Converters](PowerConverters-1.7.10-3.0.0.32.jar) Unloaded->Constructed->Pre-initialized
    JotatosPracticalities{0.2.5} [Practicalities](practicalities-1.7.10-0.2.5.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized
    RandomThings{2.1.6} [Random Things](RandomThings-2.1.6.jar) Unloaded->Constructed->Pre-initialized
    RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    xreliquary{1.2} [Reliquary](Reliquary-1.2.jar) Unloaded->Constructed->Pre-initialized
    simplyjetpacks{1.2.0} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized
    StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized
    thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.6a.jar) Unloaded->Constructed->Pre-initialized
    thaumicenergistics{0.8.7b} [Thaumic Energistics](thaumicenergistics-0.8.7b.jar) Unloaded->Constructed->Pre-initialized
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-33.jar) Unloaded->Constructed->Errored
    TiCTooltips{1.1.11b} [TiC Tooltips](TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized
    WailaHarvestability{1.1.0} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    denseores{1.0} [Dense Ores](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.

**Comment by TheSlimeMan** [comment]
This is a similar thing that I am dealing with, I don't know either.

**Comment by Mattk4355** [comment]
Just noticed that apparently I forgot to disable Optifine. Going to have to disable it and try again. Doubt that's what's causing it, but you have to test every possibility.

**Comment by TheSlimeMan** [comment]
ikr

**Comment by SethWilliamson** [comment]
It appears to be due to changes in TC 4.2.2. Note that the MCF page lists dependency on TC 4.1. TE was working well for me in TC 4.2.1, but recent changes to TC seem to require some patching here.

**Comment by SethWilliamson** [comment]
[Build #34 (21-Dec-2014 19:02:42)](http://jenkins.nekokittygames.com:8080/view/Thaumic%20Explorer/job/Thaumic%20Explorer/) is working for me with TC 4.2.2.1
